package com.milan.ai_code_reviewer;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;
import org.springframework.web.reactive.function.client.WebClientResponseException;

import java.util.List;
import java.util.Map;

@Service
public class AiService {

    private final WebClient webClient;

    public AiService(@Value("${groq.api.key}") String apiKey) {
        this.webClient = WebClient.builder()
                .baseUrl("https://api.groq.com/openai/v1")
                .defaultHeader("Authorization", "Bearer " + apiKey)
                .defaultHeader("Content-Type", "application/json")
                .build();
    }

    // ✅ Generate the AI review using Groq
    public String generateReview(String diff) {
        String prompt = """
                You are a senior software engineer.
                Provide a detailed, constructive code review for this Pull Request diff.
                Identify:
                - Bugs
                - Code smells
                - Potential issues
                - Refactoring suggestions
                - Security risks

                Use clear bullet points and short explanations.

                DIFF:
                """ + diff;

        Map<String, Object> requestBody = Map.of(
                "model", "llama-3.3-70b-versatile",
                "messages", List.of(
                        Map.of(
                                "role", "user",
                                "content", prompt
                        )
                )
        );

        System.out.println("\n=== DEBUG: SENDING TO GROQ ===");
        System.out.println(requestBody);
        System.out.println("=================================\n");

        try {
            return webClient.post()
                    .uri("/chat/completions")
                    .bodyValue(requestBody)
                    .retrieve()
                    .bodyToMono(Map.class)
                    .map(res -> {
                        List<Map<String, Object>> choices = (List<Map<String, Object>>) res.get("choices");
                        Map<String, Object> message = (Map<String, Object>) choices.get(0).get("message");
                        return ((String) message.get("content")).trim();
                    })
                    .block();

        } catch (WebClientResponseException.TooManyRequests e) {
            System.out.println("⚠️ RATE LIMIT HIT! Retrying in 2 seconds...");
            try { Thread.sleep(2000); } catch (InterruptedException ignored) {}
            return generateReview(diff); // simple retry
        }
    }

    // ✅ Format review into clean GitHub Markdown
    public String formatReview(String rawResponse) {
        return """
                ### ✅ AI Code Review Report

                %s

                ---

                **Notes**
                - This is an automated review.
                - Please validate suggestions before applying.

                _Generated by AI Code Reviewer_
                """.formatted(rawResponse.trim());
    }

    // ✅ Generate an AI-based Risk Score (0–100)
    public int generateRiskScore(String fullReviewText) {
        String prompt = """
                You are an expert code reviewer.
                Based on the following review text, evaluate how risky this Pull Request is.

                Consider:
                - Potential bugs
                - Core logic changes
                - Security risks
                - Urgency for fixes
                - Overall safety

                Return ONLY a number between 0 and 100.
                No explanation. Only the number.

                REVIEW:
                """ + fullReviewText;

        Map<String, Object> requestBody = Map.of(
                "model", "llama-3.3-70b-versatile",
                "messages", List.of(
                        Map.of("role", "user", "content", prompt)
                )
        );

        try {
            String result = webClient.post()
                    .uri("/chat/completions")
                    .bodyValue(requestBody)
                    .retrieve()
                    .bodyToMono(Map.class)
                    .map(res -> {
                        List<Map<String, Object>> choices =
                                (List<Map<String, Object>>) res.get("choices");
                        Map<String, Object> message =
                                (Map<String, Object>) choices.get(0).get("message");
                        return ((String) message.get("content")).trim();
                    })
                    .block();

            // Extract first integer we see, clamp to [0, 100]
            int parsed = Integer.parseInt(result.replaceAll("[^0-9]", ""));
            if (parsed < 0) parsed = 0;
            if (parsed > 100) parsed = 100;
            return parsed;

        } catch (Exception e) {
            System.out.println("⚠️ Risk score generation failed: " + e.getMessage());
            return 50; // sensible fallback (medium risk)
        }
    }
}
